cesium/calendarium

.gitignore
components/ActiveLink/ActiveLink.tsx
components/ActiveLink/index.ts
components/Navbar/Navbar.tsx
components/Navbar/navbar.module.scss
styles/globals.css

This component show what's the current page he is accessing in the Navbar

Add ActiveLink component to improve user experience

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Made the README actually presentable, your welcome xD
- Added Code Of Conduct
- Moved contributing details into a Contributing Guide
- Improved features overview

Improve `README.md`

---

components/CheckBox/CheckBox.tsx
components/CheckBox/checkbox.module.scss
components/SelectSchedule.tsx
pages/index.tsx
pages/schedule.tsx
styles/Home.module.css
styles/schedule.module.css

Improved the filters layout by separating the sub-categories into separate dropdown menus and making them overlap the calendar component when opened.
**Preview:**
**Mobile:**

Improve Filters Layout

---

components/CheckBox/CheckBox.tsx
components/SelectSchedule.tsx

Save the currently checked boxes to local storage to be displayed/used after leaving/refreshing the page

Persistant Checkboxes

---

components/CheckBox/CheckBox.tsx
components/EventModal/EventModal.tsx
data/events.json

@Carlos-oficial Implemented a Select All feature that allows the users to select all courses in a semester for each semester of each year. I contributed with the styling and design and also made improvements and bug fixes, like adding compatibility for saving the `Select All` checkboxes on local storage to remember the user's choices.
Also added some UMinho events, namely the start and end of each semester, according to the official 2022/2023 calendar from UMinho. 
**Preview:**

Select All Feature

---

components/EventModalShift/EventModalShift.tsx
components/EventModalShift/index.ts
package-lock.json
package.json
pages/index.tsx
pages/schedule.tsx
styles/Home.module.css
styles/globals.css
styles/schedule.module.css

Made significant improvements to the UI and UX:
- Use `Inter` font on `Calendar` component;
- Improve design of events;
- Change Schedule `Calendar` layout to work_week (mon-fri);
- Update the `EventModal` design (it now uses [MUI](https://mui.com/material-ui/react-modal/) Modal);
- Add `EventModalShift` (pop ups for the Schedules page);
- Change Schedule Events colors, with different shades of CeSIUM's orange for T/TP classes;
- Potentially fix the bug issued here: #66 .
**Preview:**
Improved popup with dynamic elements
Improved Schedules view
New popup with class information

Major Improvements to UI & UX

---

package-lock.json
pages/index.tsx
pages/schedule.tsx

Finally fixed the bug where the Schedule page wouldn't render properly on Mobile (#66). Thank you @MarioRodrigues10 for helping with how to test this ;)

Bug Fix: Schedule on Mobile

---

data/events.json
data/shifts.json

Fixed the PL7 LI2 shift room and added a SO event.
- Fix LI2 PL7 shift
- Add SO event

Fix Shift & Add Event

---

HELPING_GUIDE.md
README.md

Made an `Helping Guide` that gives step-by-step instructions on how to make a pull request for Calendarium to add, update or fix events or shifts. This will allow the users to fix problems or add missing events by themselves, resulting in faster updates to our calendar. This also invites the students to directly contribute and interact with CeSIUM, while also learning core concepts.
- add helping guide
- mention new guide and features on readme

Add Helping Guide

---

components/CheckBox/checkbox.module.scss
components/EventModal/EventModal.tsx
components/EventModalShift/EventModalShift.tsx
components/SelectSchedule/selectschedule.module.scss
package-lock.json
styles/globals.css
styles/schedule.module.css

Made some tweaks to the CSS to improve UI coherence, changing border-radius to 24px on the Modal's and the filters, which is the radius we use on the navbar and footer and that follows the Tailwind standard of multiples of 4. Also made other small tweaks.
- imporove: ui coherence
- fix

Improve UI Coherence

---

data/events.json

Added the MNOnL project's due date, May 19th.

Add MNOnL Event

---

HELPING_GUIDE.md

Clarified how to check the `filterId` of each class and changed the events.json example to a more explicit one.

Clarify Helping Guide

---

data/events.json

Added the LEI Época Especial exams.

Add Época Especial Exams

---

components/EventFilters/EventFilters.tsx
components/Layout/Layout.tsx
components/Layout/layout.module.scss
components/Notifications/Notifications.tsx
components/Notifications/index.tsx
components/ScheduleFilters/ScheduleFilters.tsx
components/Sidebar/Sidebar.tsx
data/notifications.json
pages/schedule.tsx
tailwind.config.js

This is a big update that aims to add a notification feature to inform our students of when Calendarium is updated with fresh new information.
**This is how it currently works:**
- The notifications are saved in a JSON file, where we can easily add more.
- Each notification contains a type, a description and a date.
- Only notifications from the last 7 days (can be changed) are showed to the user.
- The notifications that the users dismiss are saved into local storage, meaning that they will not appear again the next time they open the website. Each notification is identified by its date, since it includes date and time, which is something that will always differ between notifications.
**Q:** If we have 100 notifications accumulated in the JSON, will a new user receive them ALL?
**A:** …

Add Notifications

---

components/EventFilters/EventFilters.tsx
components/ScheduleFilters/ScheduleFilters.tsx

- bug fix
- additional fixes
- fix

Fix Bug Fix

---

scraper/README.md
scraper/main.py
scraper/modules/README.md
scraper/modules/course_scraper.py
scraper/modules/schedule_scraper.py
scraper/modules/subjects_scraper.py

* dealing with some possible errors
* dealing with just 1st semester schedules

Scraper Corrections

---

components/EventFilters/EventFilters.tsx
components/EventModal/EventModal.tsx
components/Notifications/Notifications.tsx
components/ShiftModal/ShiftModal.tsx
components/Sidebar/Sidebar.tsx

Improved the typescript in the `Notifications` component and removed some left-over unnecessary code.
- improve typescript
- remove unnecessary code

Improve Typescript

---

components/EventFilters/EventFilters.tsx
components/EventFilters/eventfilters.module.scss
components/Notifications/Notifications.tsx
components/ScheduleFilters/ScheduleFilters.tsx
components/ScheduleFilters/schedulefilters.module.scss
data/events.json
data/filters.json
data/notifications.json
pages/index.tsx

Added events from UMinho's 2022/2023 academic year, as well as two notifications that will be shown from 01/09/23 notifying this update.
Also made a little update to notifications, now they'll be sorted from oldest to newest - which just makes sense, in my opinion.
- data: eventos de atividades letivas
- update: sort notifications from oldest to newest

Always Active Events Feature & Others

---

HELPING_GUIDE.md
components/EventModal/EventModal.tsx
components/ShiftModal/ShiftModal.tsx
data/events.json
dtos/index.ts
pages/index.tsx
pages/schedule.tsx

Fixed the EventModal and ShiftModal transitions (when closing the modal would immediatly dissapear and have no closing transition). Also transitioned the code to TailwindCSS.
While at it improved the typescript by using the IEventDTO and IShiftDTO interfaces, avoiding having to change the code in various places when adding a new property to an object.
Additionally, added support for links for Events. Now, any event can include a link (like SEI and JOIN previously did) by adding a `link: "https://link.here"` property to the event object in the JSON.
- improve typescript
- improve ui & ux

Improve Modals, Add Links to Events, Improve Typescript

---

components/Notifications/Notifications.tsx
data/notifications.json
tailwind.config.js

Improved the text of the Color Themes notification and added a width limit of 80% for notifications on non-mobile screens.
- improve notification text
- limit notification width

Improve Notifications

---

pages/index.tsx
pages/schedule.tsx

| From | To |
|--------|--------|
| ![image](https://github.com/cesium/calendarium/assets/36338391/31c20718-1ec6-4e2f-b1bd-523ec12571e0) | ![image](https://github.com/cesium/calendarium/assets/36338391/e50ce4a6-9620-4145-97a4-04118297d8fc)|

Change schedule time gutter from 12h to 24h format

---

scraper/modules/subjects_scraper.py

Warning when a short name is used more than once time

Warning User for repeated short names

---

pages/api/export/events.tsx

Updated the events API to fetch the events from Google Sheets and NOT events.json

Fix Events API

---

.github/workflows/main.yml
.github/workflows/style.yml
scraper/.gitignore
scraper/main.py
scraper/subjects.json
scraper/subjects_short_names.json

Created and tested a new workflow in `main.yml` that makes it so that the Calendarium Scraper is executed every 7 days, automatically creating an automated PR with the new and updated shifts. If no differences are detected between versions the pull request is automatically closed.
Also improved the CI Style check so that it automatically formats the code with Prettier, instead of simply saying it is not complying with the Prettier standard.

Run Scraper as Github Action & Improve CI Style Check

---

data/notifications.json

Added a notification informing of the newly added information regarding the allocated places for the upcoming 1st, 2nd and 3rd years tests.
Added additional notification reminding new users of how to check more information about an event, including how to check info. like the place where it will happen.

chore: add notification

---

components/EventModal/EventModal.tsx
components/FilterBlock/FilterBlock.tsx
components/Layout/Layout.tsx
components/Settings/Settings.tsx
components/ShiftModal/ShiftModal.tsx
components/Sidebar/Sidebar.tsx
pages/index.tsx
pages/schedule.tsx

Made some general UI improvements, namely:
**Added shadow rings to sidebar elements:**
This helps to better define elements with a white background and a shadow, being most noticeable on high resolution screens like on mobile.
| After | Before |
| ------- | ---------- |
| ![Screenshot_20231028_112843](https://github.com/cesium/calendarium/assets/80540164/09a2f9b1-c816-4450-87f9-382e8f22c830) | ![Screenshot_20231028_112850](https://github.com/cesium/calendarium/assets/80540164/c800961b-22eb-4596-b229-2b85ed8f86c6) |
**Changed the way overlapping events are displayed in /schedule:**
For this I had to implement a trick that subtracts 1 minute to the end time of an event, refer to the comment on the code.
| After | Before |
| ------- | ---------- |
| …

style: general UI improvements

---

README.md
components/CalendarExportModal/CalendarExportModal.tsx
components/ClearScheduleButton/ClearScheduleButton.tsx
components/EventFilters/EventFilters.tsx
components/EventModal/EventModal.tsx
components/ExportButton/ExportButton.tsx
components/FilterBlock/FilterBlock.tsx
components/Layout/Layout.tsx
components/Layout/layout.module.scss
components/Notifications/Notifications.tsx
components/ScheduleFilters/ScheduleFilters.tsx
components/Settings/Settings.tsx
components/ShareButton/ShareButton.tsx
components/ShareButton/index.ts
components/ShareModal/ShareModal.tsx
components/ShareModal/index.ts
components/ShiftModal/ShiftModal.tsx
components/Sidebar/Sidebar.tsx
components/Sidebar/sidebar.module.scss
components/Themes/Themes.tsx
styles/globals.css

Added a share feature that allows users to share their selected subjects or their schedule with friends or another device.
Improved the UI in general, but especially in the Sidebar.

feat: add share feature & improve ui

---

data/notifications.json

Added two notifications to informt the users about updated information on future events, more specifically the addition of time and place information.

chore: add updated info. notifications

---

package-lock.json
package.json
styles/globals.css

Update `react-big-calendar` in hopes of fixing `eventPropGetter` `undefined` bug.

chore: update `react-big-calendar`

---

components/Layout/Layout.tsx

Add missing tailwind classes that were not included when doing the fix in #213. (Shame @ruioliveira02, shame).

fix: add missing tailwind classes

---

.gitignore

Usually, I create my virtual environments under a `.venv` directory.

chore: improve gitignore

---

package-lock.json

Litterally just ran `npm audit fix`.

chore: fix package vulnerabillities

---

data/shifts.json

fix: duplicated shift

---

scraper/modules/create_filters.py

PR to fix the [problem of OT shifts missing for LI4](https://github.com/cesium/calendarium/pull/236#issuecomment-2381429061)

fix: scrape 'OT' shifts

---

.github/workflows/main.yml

chore: enhance scraper workflow/action

---

.github/workflows/main.yml

This reverts commit f5f19303d4d11ded506934bfa23c103a8300fdfd.

Revert "chore: enhance scraper workflow/action (#239)"

---

styles/globals.css

The Node version fix didn't fix this, so I'm removing it again.

fix: wrong day being highlighted

---

components/Layout/Layout.tsx
components/Sidebar/Sidebar.tsx

fix: wrong logo when on "dark" appearance setting

---

hooks/useColorTheme.ts

The dumbass that had the bright idea to make Calendarium store ALL subject colors in local storage, even if they were all default values, (aka me) didn't think of the fact that if a new subject is added and the array of colors in local storage was already initialized before, selecting this new subject and trying to customize it's color will result in a crash because it's value doesn't exist in local storage.
To fix this, I did what I should have done in the first place: only store in local storage the color values that were actually changed and assume the default values for those not present in local storage.
Your majesties, kindly pardon my honest mistakes 🙏
P.S. I have tested this fix with the exact configuration that made the bug occur, provided by @ruilopesm, and it worked. Have also …

fix: bug on subject color storage

---

components/FilterBlock/FilterBlock.tsx
components/Sidebar/Sidebar.tsx

Fixed this (no shadow):
Removed sidebar border radius on desktop because of this:
- **fix: no shadow**
- **feat: remove border radious**

feat: small style fix/improvement
