cesium/calendarium

components/Modal.tsx

Displaying the title of an event on its description it's useless, so that, we should remove it.

Remove event description

---

components/CheckBox/CheckBox.tsx
components/CheckBox/checkbox.module.scss
components/EventModal/EventModal.tsx
components/EventModalShift/EventModalShift.tsx
components/FeedbackForm/FeedbackForm.tsx
components/Navbar/navbar.module.scss
components/SelectSchedule/SelectSchedule.tsx
components/SelectSchedule/index.ts
components/SelectSchedule/selectschedule.module.scss
package-lock.json
package.json
pages/index.tsx
pages/schedule.tsx
styles/schedule.module.css

Added a `Clear Schedule` button that allows the user to easily clean all he's Schedule selections. This was also a feature suggested by users and it's useful for changing schedules when a new semester begins or to play around with possible schedules.
Other  improvements:
- Turn `SelectSchedule` into a component with a scss module
**Preview:**

`Clear Schedule` Feature

---

components/EventModalShift/EventModalShift.tsx
data/events.json
pages/schedule.tsx

Added all the events known so far for 2nd year 2nd semester and made some improvements to the shift view on Schedule page.
Now the shift title will be composed of the class acronym and the full class title will only be shown on the Modal.
- Add 2year 2sem events
- Improve Schedule view

Add 2y2s events & Improve shift view

---

data/shifts.json

Changed the room of the T2 IO shift from 0.20 to 0.08 based on feedback from the Calendarium form.

Fix room of T2 IO shift

---

components/CheckBox/CheckBox.tsx

Fixed a bug regarding the display of the MEI filter on the Events page, the 2nd year of MEI is composed of only one group of events and it was being wrongly separated into 1st and 2nd semesters, a change that I made on #91. It's fixed now, I had to separate some elements because of these unique attributes which increases the amount of reused code, but for now it's the best way to do it.

Bug Fix on Events Filter

---

components/EventFilters/EventFilters.tsx
components/ScheduleFilters/ScheduleFilters.tsx

Fixed a bug in the Event and Schedule filters where selecting a checkbox would force the Collapse element to "collapse" immediatly. This for some reason happens when using a random generator for the key values, I was using a random generator to make sure the keys of all elements were always unique. The fix was to just not use a random generator and actually think of a mathematical way to keep the keys different between elements.

Bug Fix in Filters :rotating_light: 

---

pages/index.tsx
pages/schedule.tsx

Fixed a bug whose origin is still unknown that causes the "theme" parameter in local storage to be set to "null" causing the event colors to display a neutral black color. Fixed this in two ways:
1. Check if the "theme" parameter exists and set it to "Modern" by default;
2. If the "theme" parameter exists, check if it falls under "Modern", "Classic" or "Custom" and set it to the default ("Modern") if it doesn't.

fix: events display neutral color

---

components/EventModal/EventModal.tsx
components/ShiftModal/ShiftModal.tsx

Made it so the `EventModal` and `ShiftModal` have a dynamic width, instead of a fixed one. The modal will have a minimum width of 18rem (same as previously) and only expand to a `w-fit` if it's needed. This is particularly useful on `EventModal`, since it can house a link with unpredictable size. A great example is the current Code Week event, where the link is wrapping down because of the fixed width.

feat: dynamic modal width

---

.github/workflows/trello.yml
README.md

This action allows to automatically link a Trello Card with a PR by adding a link to an existing card anywhere in the PR body. Most importantly, it automatically moves the Trello Card to "Doing", "Review" or "Done" if the PR is a draft, is opened or is closed, respectively.
The idea would be to implement this action on all the repositories we currently have on Trello. t

feat: add trello integration action

---

components/EventModal/EventModal.tsx
pages/api/export/events.tsx
pages/index.tsx
utils/index.ts

Fixed a bug that caused events with the `groupId` parameter set to `0` to be considered invalid. This happened because the value `0` would be read as `false` in the if condition.
In the process of solving this, I also made some improvements to the way dates and times are shown in `EventModal`, particularly for events that extend for multiple days AND have a specific start hour and end hour, for example Karaoke, that goes from 28/11 at 21:00 to 29/11 at 02:00.
Also made the event location a link that takes the the user to Google Maps and automatically searches for the location. 
- fix: events with `groupId` set to `0` won't show
- style: improve the way dates are displayed

fix: bug in event fetching for `groupId = 0`

---

components/Notifications/Notifications.tsx
package-lock.json
package.json

Added compatibility for markdown in the notification descriptions, this markdown is taken as a string and converted to html and then JSX. To achieve this, I installed the following (very light) npm package: [markdown-to-jsx](https://www.npmjs.com/package/markdown-to-jsx).

feat: markdown for notifications

---

scraper/modules/course_scraper.py
scraper/modules/subjects_scraper.py

The subject "Mecânica Quântica" wasn't being found because on the last week of the semester it wasn't no more present on the official schedule.
To prevent this, the scraping month and day were hard coded to the half of the semester.

fix: scraper doesn't find some subjects

---

components/CalendarExportModal/CalendarExportModal.tsx
components/ClearScheduleButton/ClearScheduleButton.tsx
components/DarkModeToggler/DarkModeToggler.tsx
components/DarkModeToggler/index.ts
components/EventModal/EventModal.tsx
components/ExportButton/ExportButton.tsx
components/FilterBlock/FilterBlock.tsx
components/Install/Install.tsx
components/Layout/Layout.tsx
components/NavigationPane/NavigationPane.tsx
components/Settings/Settings.tsx
components/ShareButton/ShareButton.tsx
components/ShareModal/ShareModal.tsx
components/ShiftModal/ShiftModal.tsx
components/Sidebar/Sidebar.tsx
components/Themes/Themes.tsx
package-lock.json
package.json
pages/_app.tsx
pages/_document.tsx
pages/schedule.tsx
styles/globals.css
tailwind.config.js

Implemented a dark mode fully with TailwindCSS and the help of the `next-themes` npm package that handles toggling, saving preference to local storage, etc.
**Preview:**

feat: dark mode

---

.gitignore
scraper/modules/subjects_short_names_scraper.py
scraper/subjects.json
scraper/subjects_short_names.json

Adding this to the scraper code makes sure that the problem of having two pairs of equal short names (PI - Programação Imperativa, PI - Projeto Informática, IA - Inteligência Artificial, IA - Inglês Académico) never happens again, even if we clean the scraper "cache", i.e. the `subjects_short_names.json` and `subjects.json` files.

fix: add `ProjInf` and `IngA` short names manually

---

data/shifts.json

Alteração da sala de MNoL turno PL7.
Segue-se o email enviado pela professora:
```
Caros alunos,
Gostaria de informar que houve uma modificação na sala de aula para o turno PL7 (6ª feira das 11h às 13h). A partir de agora, as aulas serão realizadas no Edifício 2, Sala 1.10.
Esta mudança é válida para todo o semestre.
Atenciosamente,
Elsa Silva
```

Update shifts.json: MNoL PL7 room

---

data/shifts.json
pages/index.tsx
pages/schedule.tsx
utils/index.ts

Finally was able to recreate a weird bug that had been happening to some people. The bug consisted on the app crashing when reaching a certain month. After recreating the `localStorage` of a user with this problem I was able to recreate the bug on my machine. After exploring and messing with the different parameters I finally got it:
The colors defined for each course year + the colors defined for special events (like UMinho, CeSIUM, SEI, etc) are stored in `localStorage`, when a user tries to change the app theme based on "Year". From this point onward, the app will prioritize the values in `localStorage`, instead of the default values, as long as the "Year" option for the custom theme is selected. Recently a new special event color was added to Calendarium, the Bugsbyte color, which …

fix: patch `undefined` error

---

components/CustomToolbar/CustomToolbar.tsx
pages/_document.tsx
styles/globals.css

Changed the today button in the calendar toolbar so that it reads "Today" instead of the previous sun icon that could be confused for a light/dark mode toggle and was unclear in general. Also moved font and icon imports to Head for improved efficiency.
- **feat: import fonts and icons in head**
- **feat: change today button look**

feat: improve today button in toolbar for better understanding

---

components/FilterBlock/FilterBlock.tsx

| | |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/c3af2670-33c7-4c71-8e4b-a9f74febf482) | ![image](https://github.com/user-attachments/assets/932a5124-34ca-445d-8593-1cc6c669df8c) |
Contexto: LI4 não tem turnos este ano.

feat: display 'information not available' message for empty collapses in /schedule

---

data/filters.json
data/shifts.json

The scraper is having problems adding the LI4 shifts to `filters.json` and is not picking up a shift for "Sustentabilidade Ambiental, Social e Económica". Both these problems were manually fixed in #226 and somewhere else along with other PR. However, every time the scraper runs it removes these manual changes when generating the JSON files, so we have to be aware of that from now on while the problem isn't fixed in the scraper itself.
#235 was merged by @ruilopesm because he didn't know this, so I'm adding the required changes back.

fix: re-add shifts removed by scraper

---

styles/globals.css

So... I had a typical case of skill issue on the last PR and there's a line that shouldn't be there.

fix: remove line that shouldn't be there :D

---

components/CustomToolbar/CustomToolbar.tsx
components/Layout/Layout.tsx
components/MoreButton/MoreButton.tsx
components/MoreButton/index.ts
components/Sidebar/Sidebar.tsx
contexts/AppInfoProvider.tsx
pages/index.tsx
pages/schedule.tsx
styles/events.module.css
styles/globals.css
styles/schedule.module.css
tailwind.config.js

Major improvements to overall layout, stretching the calendar component to reach the corners of the screen and use the most screen real estate as possible, both on desktop and mobile, while also reducing font-size for better readability:
| Events | Schedule |
| - | - |
| ![Screen Shot 2025-01-08 at 02 23 26](https://github.com/user-attachments/assets/6c8c09b7-2035-45ed-a0de-0de9c2cf0297) | ![Screen Shot 2025-01-08 at 02 23 37](https://github.com/user-attachments/assets/a94c1f62-0094-4fc9-a62b-32939ca53b3d) |
| ![Screen Shot 2025-01-08 at 02 25 25](https://github.com/user-attachments/assets/1e47074c-1a42-4352-a861-ead700c21c4a) | ![Screen Shot 2025-01-08 at 02 25 29](https://github.com/user-attachments/assets/126723c3-8f77-4dcc-bbb5-e56d8f429cbf) |
The missing events form link and the …

feat: layout improvements

---

components/CalendarExportModal/CalendarExportModal.tsx
components/EventFilters/EventFilters.tsx
components/FilterBlock/FilterBlock.tsx
components/Layout/Layout.tsx
components/ScheduleFilters/ScheduleFilters.tsx
components/ShareButton/ShareButton.tsx
components/ShareModal/ShareModal.tsx
components/Sidebar/Sidebar.tsx
components/Themes/Themes.tsx
contexts/AppInfoProvider.tsx
data/mei_perfis.ts
pages/index.tsx
types/index.ts

Refactored `FilterBlock` in order to **completely generalize its usage** and allow for the long awaited **separation of "Opção UMinho" subjects from the regular ones** and the **organization of the subjects of each profile in the master's degree** in its own category.
| | |
| - | - |
| ![image](https://github.com/user-attachments/assets/f22bf1ce-b980-4c66-bd4a-37040a9c4028) | ![image](https://github.com/user-attachments/assets/25fae2e6-6bbe-43fa-a809-17181d8907fe) |
This refactor was made possible by using a **recursive** component, `RenderLayer`, that calls itself for each sublayer. This component receives information in the following specification, that itself is also recursive:
```ts
export interface Layer {
title: string;
sublayers?: Layer[];
checkboxes?: CheckBox[];
}
```
The …

refactor: apply recursion to `FilterBlock`

---

styles/globals.css

Noticed that the HexColorPicker width was not quite right for some reason, so fixed it.

fix: hex color selector width
